Use cloudnativeapps version of boot2docker iso

diff --git a/docker b/docker
--- a/docker
+++ b/docker
@@ -174,7 +174,11 @@ EOF
     "$NODE_BIN" -e "$FWD_SERVER_JS" &
 }
 
-function docker-download-iso () {
+function docker-boot2docker-iso-url () {
+    # use cloudnativeapps version for vmware support for now
+    echo "https://github.com/cloudnativeapps/boot2docker/releases/download/v1.4.1-vmw/boot2docker-1.4.1-vmw.iso"
+    exit 0
+
 GET_LATEST_BOOT2DOCKER_TAG="$(
 cat << EOF
 require("https").get({
@@ -194,20 +198,29 @@ require("https").get({
 });
 EOF
 )"
-    ISO_PATH="$VMDIR/boot2docker.iso"
-    LATEST_BOOT2DOCKER_TAG="$("$NODE_BIN" -e "${GET_LATEST_BOOT2DOCKER_TAG}")"
+    local LATEST_BOOT2DOCKER_TAG="$("$NODE_BIN" -e "${GET_LATEST_BOOT2DOCKER_TAG}")"
     if [[ -n "$LATEST_BOOT2DOCKER_TAG" ]] && [[ "$LATEST_BOOT2DOCKER_TAG" != "v0.0.0" ]]; then
-        echo "Downloading boot2docker $LATEST_BOOT2DOCKER_TAG..."
-        curl -L --progress-bar "https://github.com/boot2docker/boot2docker/releases/download/${LATEST_BOOT2DOCKER_TAG}/boot2docker.iso" > "$ISO_PATH.new"
-        if [[ $? == 0 ]]; then
-            rm -f "$ISO_PATH" || true
-            mv "$ISO_PATH.new" "$ISO_PATH"
-            echo "Downloaded boot2docker $LATEST_BOOT2DOCKER_TAG!"
-        else
-            echo "Failed to download!"
-            exit 1
-        fi
+        echo "https://github.com/boot2docker/boot2docker/releases/download/${LATEST_BOOT2DOCKER_TAG}/boot2docker.iso"
     else
+        exit 1
+    fi
+}
+
+function docker-download-iso () {
+    local ISO_URL="$(docker-boot2docker-iso-url)"
+    if [[ -z $ISO_URL ]]; then
+        exit 1
+    fi
+
+    local ISO_PATH="$VMDIR/boot2docker.iso"
+    echo "Downloading boot2docker..."
+    curl -L --progress-bar "$ISO_URL" > "$ISO_PATH.new"
+    if [[ $? == 0 ]]; then
+        rm -f "$ISO_PATH" || true
+        mv "$ISO_PATH.new" "$ISO_PATH"
+        echo "Downloaded boot2docker!"
+    else
+        echo "Failed to download!"
         exit 1
     fi
 }
@@ -222,18 +235,17 @@ function docker-vm-init () {
     local ID_RSA_PUB="$(cat ~/.ssh/id_rsa.pub)"
 ssh $SSH_OPTIONS $SSH_DOCKER_HOST -- << DOCKER_INIT
 
-if blkid -c /dev/null | grep boot2docker-data &>/dev/null; then
-    exit 0
+if ! blkid -c /dev/null | grep boot2docker-data &>/dev/null; then
+    echo -e "\033[0;32mFormatting /dev/sda\033[0m"
+    echo -e "n\np\n1\n\n\nw\n" | sudo fdisk /dev/sda
+    sudo mkfs.ext4 -L boot2docker-data /dev/sda1
+    sudo mkdir /mnt/sda1
+    sudo mount -t ext4 /dev/sda1 /mnt/sda1
+    sudo mkdir -p /mnt/sda1/var/lib/boot2docker
 fi
 
 TCL_REPO_BASE=http://tinycorelinux.net/5.x/x86
-
-echo -e "\033[0;32mFormatting /dev/sda\033[0m"
-echo -e "n\np\n1\n\n\nw\n" | sudo fdisk /dev/sda
-sudo mkfs.ext4 -L boot2docker-data /dev/sda1
-sudo mkdir /mnt/sda1
-sudo mount -t ext4 /dev/sda1 /mnt/sda1
-sudo mkdir -p /mnt/sda1/var/lib/boot2docker
+WORKING_DIR="\$(pwd)"
 
 echo -e "\033[0;32mPushing ssh keys\033[0m"
 mkdir /home/docker/.ssh
@@ -243,7 +255,6 @@ sudo touch /mnt/sda1/var/lib/boot2docker/.ash_history
 sudo chown docker /mnt/sda1/var/lib/boot2docker/.ash_history
 chmod 600 /home/docker/.ssh/authorized_keys
 cat /home/docker/.ssh/authorized_keys | grep "$ID_RSA_PUB" || echo "$ID_RSA_PUB" >> /home/docker/.ssh/authorized_keys
-WORKING_DIR="\$(pwd)"
 cd /home/docker
 ln -sf /var/lib/boot2docker/.ash_history .ash_history
 sudo tar -cf /mnt/sda1/var/lib/boot2docker/userdata.tar .ssh .ash_history
@@ -257,17 +268,18 @@ echo -e "\033[0;32mDownloading additional modules\033[0m"
 sudo mkdir -p /mnt/sda1/var/lib/boot2docker/tcz
 
 sudo curl -L -q -o /mnt/sda1/var/lib/boot2docker/tcz/cifs-utils.tcz \$TCL_REPO_BASE/tcz/cifs-utils.tcz
+sudo curl -L -q -o /mnt/sda1/var/lib/boot2docker/tcz/ncurses-common.tcz \$TCL_REPO_BASE/tcz/ncurses-common.tcz
+sudo curl -L -q -o /mnt/sda1/var/lib/boot2docker/tcz/ncurses-terminfo.tcz \$TCL_REPO_BASE/tcz/ncurses-terminfo.tcz
+sudo curl -L -q -o /mnt/sda1/var/lib/boot2docker/tcz/ncurses-utils.tcz \$TCL_REPO_BASE/tcz/ncurses-utils.tcz
+sudo curl -L -q -o /mnt/sda1/var/lib/boot2docker/tcz/ncurses.tcz \$TCL_REPO_BASE/tcz/ncurses.tcz
 sudo curl -L -q -o /mnt/sda1/var/lib/boot2docker/tcz/htop.tcz \$TCL_REPO_BASE/tcz/htop.tcz
 
+if [[ ! -e /usr/local/bin/vmtoolsd ]]; then
 echo -e "\033[0;32mDownloading open vmware tools\033[0m"
 sudo curl -L -q -o /mnt/sda1/var/lib/boot2docker/tcz/procps.tcz \$TCL_REPO_BASE/tcz/procps.tcz
 sudo curl -L -q -o /mnt/sda1/var/lib/boot2docker/tcz/glib2.tcz \$TCL_REPO_BASE/tcz/glib2.tcz
 sudo curl -L -q -o /mnt/sda1/var/lib/boot2docker/tcz/libtirpc.tcz \$TCL_REPO_BASE/tcz/libtirpc.tcz
 sudo curl -L -q -o /mnt/sda1/var/lib/boot2docker/tcz/libffi.tcz \$TCL_REPO_BASE/tcz/libffi.tcz
-sudo curl -L -q -o /mnt/sda1/var/lib/boot2docker/tcz/ncurses-common.tcz \$TCL_REPO_BASE/tcz/ncurses-common.tcz
-sudo curl -L -q -o /mnt/sda1/var/lib/boot2docker/tcz/ncurses-terminfo.tcz \$TCL_REPO_BASE/tcz/ncurses-terminfo.tcz
-sudo curl -L -q -o /mnt/sda1/var/lib/boot2docker/tcz/ncurses-utils.tcz \$TCL_REPO_BASE/tcz/ncurses-utils.tcz
-sudo curl -L -q -o /mnt/sda1/var/lib/boot2docker/tcz/ncurses.tcz \$TCL_REPO_BASE/tcz/ncurses.tcz
 
 sudo curl -L -q -o /tmp/squashfs-tools-4.x.tcz \$TCL_REPO_BASE/tcz/squashfs-tools-4.x.tcz
 tce-load -i /tmp/squashfs-tools-4.x.tcz
@@ -291,6 +303,7 @@ cd /tmp
 sudo mksquashfs libdnet /mnt/sda1/var/lib/boot2docker/tcz/libdnet.tcz
 sudo mksquashfs open-vm-tools /mnt/sda1/var/lib/boot2docker/tcz/open-vm-tools.tcz
 cd "\$WORKING_DIR"
+fi
 
 echo -e "\033[0;32mInstalling local boot script\033[0m"
 sudo tee /mnt/sda1/var/lib/boot2docker/bootlocal.sh << BOOT2DOCKER_INIT_SCRIPT
@@ -304,7 +317,9 @@ echo search localdomain > /etc/resolv.conf
 echo nameserver 8.8.8.8 >> /etc/resolv.conf
 echo nameserver 8.8.4.4 >> /etc/resolv.conf
 
-/usr/local/bin/vmtoolsd --background /var/run/vmtoolsd.pid
+if [[ ! -e /etc/rc.d/vmtoolsd ]]; then
+    /usr/local/bin/vmtoolsd --background /var/run/vmtoolsd.pid
+fi
 
 BOOT2DOCKER_INIT_SCRIPT
 
